### PR TITLE
TahaTheHacker-Is-A-Total-Noob.

### PR DESCRIPTION
**Pull request by MCPEPIG**
1. Learn PHP.
2. Learn PocketMine API.
3. Next time make sure your code isn't so messy, my brain and eyes hurt from looking at your code.
4. Read 1, 2, & 3.
5. Read 4.
6. Can I have a carrot? :stuck_out_tongue_winking_eye:

### CODE REVIEW

**Comment by legoboy0215** [comment]
:+1: 
NOOO.. IDK how to merge pulls :P

**Comment by jojoe77777** [comment]
You removed the changing text.

**Comment by TahaTheHacker** [comment]
Dang, But you removed the text,and that's what i need. 

The thing wasn't working is the text not changing,but messages yes,they work properly.

**Comment by legoboy0215** [comment]
:P

**Comment by TahaTheHacker** [comment]
No need fr this now, i fixed it.

**Comment by MCPEPIG** [comment]
Accepts it :stuck_out_tongue_winking_eye: Your code is super messy (Probably cause u copy and paste code) and needs serious fixing.

**Comment by MCPEPIG** [comment]
You can add back your changing text after.

**Comment by TahaTheHacker** [comment]
Yes, i copy and paste some codes, but then i change them as my code is working.

**Comment by MCPEPIG** [comment]
It doesn't matter if it works or not. Your claiming this is all your code when you just copied all of it from other plugins and edited it.

**Comment by MCPEPIG** [comment]
and you don't even understand it.

**Comment by Gamecrafter** [comment]
@TahaTheHacker You just got **#Roasted** by @MCPEPIG! :stuck_out_tongue_closed_eyes:

**Comment by jojoe77777** [comment]
@Gamecrafter You just need to stop.

**Comment by Gamecrafter** [comment]
@jojoe77777 Stay out of this, unless you want to get **#Roasted** also.

**Comment by jojoe77777** [comment]
@Gamecrafter You keep saying "#Roasted" to people, even on PM forums. It gets annoying.

**Comment by Gamecrafter** [comment]
@jojoe77777 **#Roasted** was so yesterday. Get **#burned**, mate!

**Comment by TahaTheHacker** [comment]
...

**Comment by MCPEPIG** [comment]
I think you mean #baconed

**Pull request closed without merging**
